version: "3.9"
services:
  prometheus:
    image: prom/prometheus:v2.54.0
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:10.4.8
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana_provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana_provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana_provisioning/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  grafana-data:
